### ISSUE TITLE
Possible problem with variable expansion in Roma template

### ISSUE THREAD

**Issue by martindholmes** [TEIC/Roma#10]
The template roma/templates/main.tem includes this variable intended for expansion based on the config.php file:

```
{roma_date}
```

This provides the release date in the footer of every page. However, this does not work in the installation on tei-c.org (it gets replace with an empty string), so I've had to replace it with a hard-coded value. We need to test this to see if it's a problem only on tei-c.org for some reason, or if it's not, how to fix it.

**Comment by jamescummings** [comment]
This seemed to work with the earlier version (since `{roma_date}` is in the footer once you go in. So seems strange that it doesn't get set in the latest version.  Is it not just set manually in config-dist.php? e.g. at https://github.com/TEIC/Roma/blob/master/roma/config-dist.php#L43 ?

**Comment by martindholmes** [comment]
The earlier version also has {roma_date} manually set in main.tem. config-dist.php is not there in the earlier version install (4.15); it's intended to be a template for config.php, which is identical in the two versions (4.15 and 4.18).

**Comment by jamescummings** [comment]
Ah, I see. Yes. config-dist.php is copied to config.php by a target in the Makefile.  Maybe it never worked.... I'll check the install on tei.it in case that sheds some light.

**Comment by peterstadler** [comment]
Just came across that issue and I believe it's already fixed (see the Docker image and the current installation at http://roma.tei-c.org).
`roma_date` is inserted in the build by reading the Changelog file and `roma_version` is inserted by reading the VERSION file.
