### ISSUE TITLE
Adding attributes in custom namespace and schema output

### ISSUE THREAD

**Issue by torstenroeder** [TEIC/Roma#24]
I would like to define a new attribute within a custom namespace in the global responsibility class (e.g. @my:respStatus). When I try this through Roma, the schema output (RNG) returns an error ("undefined prefix"). Is adding an attribute in own namespace allowed/intended at all, or should new attributes be defined in another way?

**Comment by peterstadler** [comment]
IMHO, there is no way to specify a namespace for attributes with current Roma (as you can—and should—for elements). Sorry, but I fear this is a feature that needs to be added to the next generation Roma and won't be added to the current version.

You can of course write (change) your ODD by hand and add something like

```xml
<classSpec ident="att.global.responsibility" type="atts" mode="change" module="tei">
    <attList>
        <attDef ident="respStatus" mode="add" ns="http://my.namespace">
            <desc>some description for myFooBar</desc>
        </attDef>
    </attList>
</classSpec>
```

**Comment by torstenroeder** [comment]
Thanks Peter!
