### ISSUE TITLE
Cannot access Roma on Website

### ISSUE THREAD

**Issue by ghost** [TEIC/Roma#28]
Hello there, 
I have recently started my PhDin History and part of it is an Edition, which I wanted to make a digital edition. In doing so I started with setting up exist-db and I wanted to follow TEI. 
I started digging and now I hit a dead end, when I wanted to specify my own ODD.( I assume tei_ms could work ....)
And now, without further ado:
when I attempt to open http://www.tei-c.org/Roma/
I get the following.
![grafik](https://user-images.githubusercontent.com/15955790/42727217-fd6237c2-87a2-11e8-8b03-d996b2c24ff1.png)
Is it me or is there sth. wrong? 

Sorry this seems so basic, I am even unsure whether I should actually ask this: Am I missing something obvious?

**Comment by ebeshero** [comment]
@kev1807 The problem is that the server supporting our Roma service is down right now--and it's part of a much larger system-wide problem! I'm sorry about that. There are other ways to customize the TEI and create an ODD, though the Roma has been a convenient way to begin that process. If you like, I can offer some advice or you could join the TEI e-mail listserv (sign up on the web here: https://listserv.brown.edu/archives/cgi-bin/wa?SUBED1=tei-l&A=1 ) . It helps to be connected to a community of TEI practitioners when you're starting out!

**Comment by kev1807** [comment]
Aaah. I was confused - yesterday even less worked- am I right? 

I fear most of my questions are quite noobish - it is quite confusing at the beginning, although having some sort of a "programming background" and working in the IT of my History department   for quite some time now. 
I am at the moment wondering so many things and I'm watching countless youtube-videos, adding to my confusion even more :-( 
I fear most of my problems are very basic ... Right now I am working through a set of Tutorials from DARIAH, which i can highly recommend for fellow starters! (They are in german.) 

I think I'll need to adjust tei_ms a little bit. I am working with a Book of Orders. So it's quite basic I think (without having seen every attribute that it delivers)I could probably go with it, without too much fuss.

**Comment by kev1807** [comment]
I can access ROMA again. 
![grafik](https://user-images.githubusercontent.com/15955790/42746548-92ce7c36-88d8-11e8-9c91-3a2c525f2d18.png)
However, something is bothering me here? I tried opening in FF, EDGE and Chrome. With enabled Adblocker, with disabled adblocker. without all addons (for the browsers) I am normally using and with all addons.

Is this still part of the aftermath or am I missing something?

**Comment by peterstadler** [comment]
It's still being fixed right now. What you downloaded is a PHP script that should've been executed on the server. It's save to throw it away ;)

**Comment by arnaudbey** [comment]
Hi there !
Still a bunch of error. For example this one, when I tried to changes some element attributes : 

`Fatal error: Uncaught TypeError: Argument 1 passed to DOMDocument::importNode() must be an instance of DOMNode, null given in /var/www/tei-roma/roma/roma.php:1042 Stack trace: #0 /var/www/tei-roma/roma/roma.php(1042): DOMDocument->importNode(NULL, true) #1 /var/www/tei-roma/roma/roma.php(1179): roma->processAddAttribute(NULL) #2 /var/www/tei-roma/roma/roma.php(326): roma->processListAddedAttributes(NULL) #3 /var/www/tei-roma/startroma.php(33): roma->run() #4 {main} thrown in /var/www/tei-roma/roma/roma.php on line 1042`

Thanks for your works guys ! :+1:

**Comment by peterstadler** [comment]
Yes, sorry that's an error that's been fixed in https://github.com/TEIC/xquery4roma/commit/4d016115c39d5b0f26ae4d2bbdcf9f3b8ca76bcd 
The main roma instance has not been updated yet, but you can use the dev version at https://roma-paderborn.tei-c.org
