### ISSUE TITLE
broken links for the module documentation in 'modules' tab

### ISSUE THREAD

**Issue by lakonis** [TEIC/Roma#32]
In the [Modules] tab, the links for the module documentation, associated with the picto 
![image](https://user-images.githubusercontent.com/9479788/54496174-ba6be800-48c2-11e9-86aa-20e76beda79e.png), are broken.

Example with the first module `analysis`, the picto targets `https://roma2.tei-c.org/release/doc/tei-p5-doc/en/html/AI.html`

**Comment by peterstadler** [comment]
Will need to wait for the build and deployment, but that commit hopefully fixes the issue

**Comment by peterstadler** [comment]
build and deployment ok, seems good to me!

@lakonis please reopen if you still encounter errors
