### ISSUE TITLE
Modules dialog broken

### ISSUE THREAD

**Issue by lueck** [TEIC/Roma#33]
Hi,

the dialog for selecting modules on [https://roma2.tei-c.org/startroma.php?mode=main](https://roma2.tei-c.org/startroma.php?mode=main) is broken.
No matter what schema I start with (e.g. the minimal one), when going to the modules dialog, the website shows some PHP errors. 

Regards
Chris

**Comment by peterstadler** [comment]
Sorry, the deployment of roma2 somehow went wrong. I just redeployed it and this should've fixed it. Many thanks for the notification!
