### ISSUE TITLE
 HTTP/1.1 503 Service Unavailable

### ISSUE THREAD

**Issue by philipphegel** [TEIC/Roma#34]
I have received a few error messages from the current version of ROMA.  As far as I can remember, this has not happened last Monday. 

"**Modules**" offers this:

Warning: file(http://xquery4roma:8080/Query/modules.xql?lang=en): failed to open stream: HTTP request failed! HTTP/1.1 503 Service Unavailable in /var/www/tei-roma/roma/roma.php on line 597

Warning: join(): Invalid arguments passed in /var/www/tei-roma/roma/roma.php on line 597

Warning: DOMDocument::loadXML(): Empty string supplied as input in /var/www/tei-roma/roma/roma.php on line 597

Fatal error: Uncaught TypeError: Argument 1 passed to DOMDocument::importNode() must be an instance of DOMNode, null given in /var/www/tei-roma/roma/roma.php:598 Stack trace: #0 /var/www/tei-roma/roma/roma.php(598): DOMDocument->importNode(NULL, true) #1 /var/www/tei-roma/roma/roma.php(655): roma->getListDom('http://xquery4r...', Object(DOMDocument)) #2 /var/www/tei-roma/roma/roma.php(530): roma->processMain(NULL) #3 /var/www/tei-roma/startroma.php(33): roma->run() #4 {main} thrown in /var/www/tei-roma/roma/roma.php on line 598

"**Add elements**" complains this way:

Warning: file(http://xquery4roma:8080/Query/classes.xql?lang=en): failed to open stream: HTTP request failed! HTTP/1.1 503 Service Unavailable in /var/www/tei-roma/roma/roma.php on line 763

Warning: join(): Invalid arguments passed in /var/www/tei-roma/roma/roma.php on line 763

Warning: DOMDocument::loadXML(): Empty string supplied as input in /var/www/tei-roma/roma/roma.php on line 763

Warning: file(http://xquery4roma:8080/Query/attclasses.xql?lang=en): failed to open stream: HTTP request failed! HTTP/1.1 503 Service Unavailable in /var/www/tei-roma/roma/roma.php on line 769

Warning: join(): Invalid arguments passed in /var/www/tei-roma/roma/roma.php on line 769

Warning: DOMDocument::loadXML(): Empty string supplied as input in /var/www/tei-roma/roma/roma.php on line 769

Warning: file(http://xquery4roma:8080/Query/datatypes.xql): failed to open stream: HTTP request failed! HTTP/1.1 503 Service Unavailable in /var/www/tei-roma/roma/roma.php on line 774

Warning: join(): Invalid arguments passed in /var/www/tei-roma/roma/roma.php on line 774

Warning: DOMDocument::loadXML(): Empty string supplied as input in /var/www/tei-roma/roma/roma.php on line 774

Warning: file(http://xquery4roma:8080/Query/macros.xql): failed to open stream: HTTP request failed! HTTP/1.1 503 Service Unavailable in /var/www/tei-roma/roma/roma.php on line 778

Warning: join(): Invalid arguments passed in /var/www/tei-roma/roma/roma.php on line 778

Warning: DOMDocument::loadXML(): Empty string supplied as input in /var/www/tei-roma/roma/roma.php on line 778

Fatal error: Uncaught TypeError: Argument 1 passed to DOMDocument::importNode() must be an instance of DOMNode, null given in /var/www/tei-roma/roma/roma.php:788 Stack trace: #0 /var/www/tei-roma/roma/roma.php(788): DOMDocument->importNode(NULL, true) #1 /var/www/tei-roma/roma/roma.php(1120): roma->processAddElements(NULL) #2 /var/www/tei-roma/roma/roma.php(323): roma->processListAddedElements(NULL) #3 /var/www/tei-roma/startroma.php(33): roma->run() #4 {main} thrown in /var/www/tei-roma/roma/roma.php on line 788

"**Change classes**":

Warning: file(http://xquery4roma:8080/Query/attclasses.xql?lang=en): failed to open stream: HTTP request failed! HTTP/1.1 503 Service Unavailable in /var/www/tei-roma/roma/roma.php on line 1196

Warning: join(): Invalid arguments passed in /var/www/tei-roma/roma/roma.php on line 1196

Warning: DOMDocument::loadXML(): Empty string supplied as input in /var/www/tei-roma/roma/roma.php on line 1196

Best,
Philipp

**Comment by jeanpaulrehr** [comment]
Indeed I am seeing the same errors today.

**Comment by peterstadler** [comment]
just restarted the two containers (roma and xquery4roma), checked  briefly, and it seems to work (again).
Sorry for the inconvenience!

**Comment by philipphegel** [comment]
Everything seems to work again. Thanks, Philipp.
