### ISSUE TITLE
part of the "Title" clipped by Roma, in a somewhat sneaky fashion

### ISSUE THREAD

**Issue by hcayless** [TEIC/Roma#8]
Relocating from https://sourceforge.net/p/tei/bugs/724/
***
When I input the following into the "Title" window in the "Customize" tab in Roma:

TEI Lite customization for Twardowski's "O czynnościach i wytworach"

and press "save", the part enclosed in quotes vanishes, so the saved XML only contains

~~~~~

<title>TEI Lite customization for Twardowski's </title>

~~~~~

**Comment by peterstadler** [comment]
Cf. discussion at https://github.com/TEIC/TEI/issues/1295

**Comment by martindholmes** [comment]
New version available for testing here:

http://www.tei-c.org/Roma-4.18/

**Comment by martindholmes** [comment]
Fix is now live. Closing the ticket.
